import type { Metadata } from "next";
import { Outfit, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cookies } from 'next/headers';
import { createClient } from '@/utils/supabase/server';

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)
  const { data: settings } = await supabase
    .from('site_settings')
    .select('whatsapp_number')
    .single()
    
  const whatsappNumber = settings?.whatsapp_number || '8801824951514'

  return (
    <html
      lang="en"
      className={`${outfit.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Navbar whatsappNumber={whatsappNumber} />
        <main className="flex-1">
          {children}
        </main>
        <Footer whatsappNumber={whatsappNumber} />
      </body>
    </html>
  );
}
